services:
  mysql_hesias:
    image: mysql:9
    restart: always
    environment:
      - MYSQL_DATABASE=library_bdd
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3306
  pma_hesias:
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
      - 8090:80
    links:
      - mysql_hesias:mysql_hesias
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
      PMA_HOST: mysql_hesias
#  app_hesias:
#    build: .
#    ports:
#      - "8082:8081"
#    environment:
#      MYSQL_HOST: mysql_hesias
#      MYSQL_PORT: 3306
#    links:
#      - mysql_hesias:mysql_hesias
