management.endpoints.web.exposure.include=*
management.endpoint.configprops.show-values=always
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
logging.level.root=INFO
logging.level.org.springframework=DEBUG
logging.level.com.hesias=INFO